### ISSUE TITLE
DCL cover self animation breaking SGO animations

### ISSUE THREAD

**Issue by ghost** [darkconsole/dse-soulgem-oven#1]
DCL has an option for your character to cover themselves when there's no item equipped in the body slot (32).

The SGO animations strip slot 32 which causes the DCL cover self animation to play which then breaks the SGO animation.

Could the ability to manually chose which slots get stripped during the SGO animations be added?

**Comment by darkconsole** [comment]
i do not really want to implement an entire slot picker cuz the entire point was to obey sexlab. currently it has the two options

strip via sexlab (normal)
strip the chest piece only

the next update will have two more choices

strip via sexlab (foreplay settings, here you could omit 32)
do not strip anything
