### ISSUE TITLE
Can't enable mod and it says Papyrus is outdated

### ISSUE THREAD

**Issue by vgfhmjfghjnfghjn** [darkconsole/dse-soulgem-oven#15]
After I try and enable the mod, & close all menus it says Papyrus is outdated and I've tried the version that came with sexlab and still no luck, I've looked everywhere for a solution and to no avail, Maybe beta 7 will fix it? or Unless you have a solution I'm all ears, Cheers!

**Comment by darkconsole** [comment]
vr?
