### ISSUE TITLE
Renaming issue

### ISSUE THREAD

**Issue by NoriNoNoroi** [darkconsole/dse-soulgem-oven#17]
The "Show Status In Actor Names", when used, names updated, then turned off, removes a NPC's name entirely when they are invited to join as a follower.  The key issue is a NPC without a name can't be selected, or enter into dialog. Example: "Illia" becomes "Illia [G=75%][M=4]" when actor status turned on, which becomes "" when actor status is turned off.  The Databank maintains the character race and refid, but the name is replaced with [G=75%][M=4] (for example).

**Comment by darkconsole** [comment]
still have not seen this myself, but i added a secondary way to get name if the first try ends up blank since there are multiple ways
