### ISSUE TITLE
FNIS issue identified

### ISSUE THREAD

**Issue by Mad1mac** [darkconsole/dse-soulgem-oven#2]
Hi, FNIS 7.6XXL for Skyrim SE provided the following note for SGO 4 Beta 6

Reading dse-soulgem-oven V400 ... 	ChAnims:9	 CTD:0.1%	 pOpt:0.1%
        NOTE: dse-soulgem-oven has at least one identical -AV defined in both 's' and '+' line

**Comment by darkconsole** [comment]
might have already fixed this. your animation count is low so you're def on an older version too. current as of today: https://github.com/darkconsole/dse-soulgem-oven/wiki/Release-Notes:-Beta-6

![image](https://user-images.githubusercontent.com/9095897/85629050-c5213b00-b636-11ea-9494-016e43a8b1a2.png)

**Comment by darkconsole** [comment]
ye, not just fixed but the animations aren't even the same anymore.
