### ISSUE TITLE
[Not a Bug] No valid oven found

### ISSUE THREAD

**Issue by MysticDaedra** [darkconsole/dse-soulgem-oven#28]
I think this could be because my character started out as male, then was changed to female via Sexlab Hormones and SD+. According to... everything I can find in-game, my character is officially female now: sexlab, Skyrim itself, any other mod that might detect sex. Unfortunately, even after trying the reset debug option in SGO4 (I am using Beta 8), I still keep getting the console message that no valid ovens can be found, and my character still won't get pregnant. Any idea on a fix?

EDIT: I'm an idiot. I tried the power menu and activated gem production, problem seems to be solved. Leaving this here in case someone else has the same problem. I might suggest for a future update that this option be extended to the MCM as well, since many folks like myself tend to eschew power menus in favor of MCM.

**Comment by darkconsole** [comment]
Yeah that data gets cached since it asks a lot of questions that wastes a lot of CPU. Use the SGO Main Menu power wheel. When not targeting anybody, it targets you, and it has choices for setting the production of gems, milks, and semens.
