### ISSUE TITLE
Mod and items not appearing in game

### ISSUE THREAD

**Issue by Clockw3rkHeart** [darkconsole/dse-soulgem-oven#29]
I installed with Vortex and all the files seem to be in the right places, built the milker in Bodyslide, nothing shows in-game regardless of new, clean, or old saves.

**Comment by darkconsole** [comment]
historically this has always been a problem with the vortex user that they somehow accidentally figure out later. i'm not one so i don't have any experience. and they tend to not report back what they did for me to copy paste to others.

so offhand, i have no suggestions.

**Comment by Clockw3rkHeart** [comment]
I'll leave this open then if that's alright and try to explain the fix if I stumble across it. Or for anyone else who knows and wants to share

**Comment by darkconsole** [comment]
no problem

**Comment by Clockw3rkHeart** [comment]
I've done nothing to the mod or game since last night, but suddenly it works now. Maybe restarting the PC had something to do with it? Either way, it's working fine.
