### ISSUE TITLE
Invalid target when using SGO 3 main menu "power"

### ISSUE THREAD

**Issue by tonitruslupus** [darkconsole/dse-soulgem-oven#3]
On some NPC they become an invalid target when trying to use SGO 4 main menu "power", it happens so far on moded NPC that I have added to the game but once I find the save just before the issue started I don't have any issues after that. is there anything can do to correct this so I do not lose progress in the game?

**Comment by darkconsole** [comment]
i've only seen that happen twice. the first time was when i removed some mod i shouldn't have and all my mods slowly exploded. that also required me going back a save like you did.

the other time was when i had a bit too much going on and i was hitting the power and then moving away before the script even had time to run.

**Comment by tonitruslupus** [comment]
well doing a little troubleshooting I am finding  that if some of the NPC can teleport to me and if they are in a middle of a sex scene or not fully out of the animation it happens, as well as fast travel it will happen, what it looks like is that it's hosing the code for those NPC when one of those 2 events happen, I am using the SGO 4 for se

**Comment by tonitruslupus** [comment]
in a previous run-through, I was using the milk machine and had the soul gem on and it totally hosed that run through animations stop working completely I tried to reinstall SGO4 and that didn't fix it, tried going back to a save before I started using the milking machines but it was totally  hosed, but when I started a new character it worked without an issue so i don't know what happened with that one

**Comment by darkconsole** [comment]
the most recent version b6 changed the way the animations check themselves and -should- more consistently be able to recover from being interrupted. being in sexlab or not yet out of sexlab is a completely valid reason it would not allow the target to work since one of the checks is asking sexlab for permission.

**Comment by tonitruslupus** [comment]
The version I downloaded I believe was the latest I downloaded it on 6-11 2020, on some of the animations just for thoughts like when a soul gem is inserted showing more of it entering and even is different positions also when birthing them it looks like it is coming out the butt, not the vagina, which if possible would love to see animations of showing that as well. 
can you run the milking machine as the same time of incubations soul gems?

**Comment by tonitruslupus** [comment]
oh, I have seen also that when you get the [g =0][m=0] by the names? I have seen it change the NPCs name to that as well as add it on like it is the last name, this happened to mrissi as well as Serena, hers was the last name, oi am not sure how much you actually do of the coding but if you know how does or if you do those issues could be a bug, just not sure yet

**Comment by darkconsole** [comment]
if still happening please reopen. been unable to replicate.
