### ISSUE TITLE
[Request] Voices option

### ISSUE THREAD

**Issue by sergei-ogan** [darkconsole/dse-soulgem-oven#35]
Thanks for the great mod.

I am a very logical person and use this mod only for soul gem growth. Of course, I think that animations and other things inserted into the womb are immersive and essential, but there are times when I want to change the voice direction.

Therefore, if there is an option to mute the voice or change it to another voice, I would enjoy spending time with it every day.

Please consider this.

**Comment by darkconsole** [comment]
voices can be assigned to actors via the sexlab mcm. sgo just asks sexlab for a voice.
