### ISSUE TITLE
Gems and Milk Spawn Outside Cell

### ISSUE THREAD

**Issue by insanityfactor** [darkconsole/dse-soulgem-oven#5]
So when an NPC or PC births/milks, both the gems and the milk do not drop at the character. At first, I thought they just weren't spawning, but then I decided to tcl and look around. Sure enough, the milk and the gems spawn consistently in the same space, outside the walls of the interior Breezehome cell, and fall into the ether and then pop back up after falling a certain distance. I tried this in multiple cells and outside, and the result is the same: the milks and gems are nowhere near the character making them. I checked out the debug logs in the console and it looks like the mod thinks everything is working fine.

**Comment by insanityfactor** [comment]
Looked a little more closely and in the console debug when it finds the node for "DropResource" it returns AnimObjectA: 0.00000. Is this a body issue then? I'm using BHUNP 3BBB, and I also don't have scaling but I was just gonna leave that be. Same issue with wanking, if that makes a difference.

**Comment by darkconsole** [comment]
the only way it appears to me that could be returning 0 would be if it cannot find the node in your skeleton.

**Comment by thrxwaway** [comment]
I know this is a long shot since this hasn't been touched in so long, but I'm having the same issue and have no idea how to fix it. I can give my load order if needed, if anyone sees this. Thanks

**Comment by darkconsole** [comment]
are you able to look at your skeleton in nifksope to confirm AnimObjectA still exists? it wouldn't be the first time i had to ask baka to stop breaking stuff lmao.

**Comment by thrxwaway** [comment]
AnimObjectA exists. Including a screenshot of my nifskope window since I don't really know what I'm looking at.
![Screenshot 2024-07-20 175911](https://github.com/user-attachments/assets/c3872fc3-28cf-42ba-b343-3c378a25d936)

**Comment by darkconsole** [comment]
sorry i just been passively thinking about it off and on. are you doing this to the player character or an npc?

if its an npc, can you confirm that npc has the correct skeleton with the node as well? as many followers do that custom race crap with custom skeletons.

**Comment by thrxwaway** [comment]
Yes, it is my PC.
